apiVersion: v1
kind: ReplicationController
metadata:
  name: task-tracker-replication-controller
spec:  
  replicas: 1
  selector:
    app: task-tracker-replication-controller
  template:
    metadata:
      labels:
        app: task-tracker-replication-controller
    spec:
      containers:
      - image: task_tracker:latest
        name: task-tracker-cntnrs
        imagePullPolicy: Never
        ports:
          - name: tsk-trkr-port
            containerPort: 8080