apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-tracker
  name: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
        env: minikube
    spec:
      containers:
      - image: task_tracker:latest
        name: task-tracker-dep-cntr
        resources: {}
        imagePullPolicy: Never
status: {}
